### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by rafaelribeiroo** [rbardini/episodic#12]
I'm using NPM v8.5.1, i've installed successfully episodic but when I type episodic on terminal, it happens:

![image](https://user-images.githubusercontent.com/19275140/193629775-609f7a79-ada5-4c0e-af29-e5e17c7b3eba.png)

Am I doing something wrong?

**Comment by rbardini** [comment]
Hi @rafaelribeiroo! Can you check if you're running Node.js v14.8+? episodic requires [top-level `await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await) support.
